name: Node.js CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          script: whoami
        #   script: |
        #     cd /var/www/mpp-rl-server
        #     git pull origin main
        #     git status
        #     npm install --only=prod
        #     sudo /var/www/infra/setup.sh
